name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Pre-Build
        run: sh ./scripts/set_api_base_in_index.sh ${{ secrets.VITE_APP_API_BASE_URL || '' }} ${{ secrets.VITE_APP_DEBUG || '' }}

      - name: Build
        run: npm run build
        env:
          VITE_APP_CALENDLY_USERNAME: ${{ secrets.VITE_APP_CALENDLY_USERNAME || '' }}
          VITE_APP_API_BASE_URL: ${{ secrets.VITE_APP_API_BASE_URL || '' }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION || '' }}
          VITE_APP_DEBUG: ${{ secrets.VITE_APP_DEBUG || '' }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
